# Javascript - Promise

## 목차



### 1. 배경 

Single Thread인 자바스크립트에서 비동기 처리를 위해 callback을 사용해왔다.

하지만

- 비동기 처리를 순차적으로 실행할 필요가 있을 경우에 중첩되어 표현되면 에러, 예외처리가 어렵다.
- 중첩으로 인한 복잡도가 증가함으로써 가독성도 나빠진다.

이러한 callback의 단점이 나타나면서 이를 해결하기 위해 새로운 패턴이 필요했다.



### 2. 정의

ES6에서는 비동기 처리를 위해 또 다른 패턴으로 Promise를 도입했다.

Promise는 callback 패턴의 단점을 보완하고 비동기 처리 시점을 명확하게 표현한다.



### 3. Callback 의 단점

 비동기 함수의 Callback에 대해 더 알아보면,

#### 	3 - 1. Callback Hell

비동기 함수의 처리 결과를 반환하는 경우, 순서가 보장되지 않기 때문에 그 반환 결과를 가지고 후속처리를 할 수 없다. 그러므로, 비동기 함수의 처리 결과에 대한 처리는 비동기 함수의 콜백 내에서 처리해야 하는데 이로 인해 Callback Hell이 생긴다.

비동기 함수의 처리 결과를 가지고 다른 비동기 함수를 호출해야 한다면 함수의 호출이 중첩되어 복잡도가 높아지는데 이를 **Callback Hell** 이라고 한다.

#### 	3 - 2. 에러 처리의 한계

```javascript
try {
    setTimeout(() => {
        throw "error";
    }, 1000);
} catch(error){
    console(error); // 호출되지 않음
}
```

위의 코드에서 try 블록 내의 setTimeout 함수가 실행되면 1초 후에 callback 함수가 실행되고 이 콜백 함수는 예외를 발생시킨다. 하지만 catch 블록에서 callback 함수에서의 예외를 잡지 못한다.

비동기 처리 함수의 callback 함수는 tick( 1초뒤 ) 이벤트가 발생하면 Task Queue로 이동한 후 호출스택이 비워졌을 때, 호출 스택으로 이동되고 처리된다. 하지만 setTimeout 함수는 비동기 처리 함수이므로 콜백 함수가 실행될 때까지 기다리지 않고 즉시 종료되어 호출 스택에서 제거된다. throw된 error는 호출자를 따라 가는데 이러면 callback 함수의 호출자가 setTimeout 함수가 아니게 되어 에러를 catch 할 수 없게된다.

setTimeout 함수의 콜백 함수를 호출한 것은 setTimeout 함수가 아니다. 따라서 setTimeout 함수의 콜백 함수 내에서 발생시킨 에러는 catch 블록에서 캐치되지 않아 프로세스는 종료된다. 

이러한 이유 때문에 Promise를 구현하게 되었다.



### 4. Promise 생성

```javascript
const promise = new Promise((resolve, reject) => {
    if(/* 비동기 작업 성공 */) {
    	resolve('result');   
    } else {
    	reject('failure reason');                        
    }
});
```

 Promise 생성자 함수는 비동기 작업을 수행할 콜백 함수를 인자로 전달받는데 이 콜백 함수는 resolve와 reject 함수를 인자로 전달받는다. 

#### 4 - 1. 상태

- pending - 대기 
- fulfilled - 성공
- rejected - 실패

```javascript
function getData() {
    return new Promise((resolve, reject) => {
        const data = 100;
        resolve(data);
    });
}

getData().then((resolvedData) => { // resolve() 의 결과 값 data를 매개변수로 전달 받는다.
    	console.log(resolvedData); // 100
	}
);
```





​     

